In [19]:
import pandas as pd

In [26]:
jd = """
Role: Data Analyst Intern

Responsibilities:
- Analyze datasets
- Work with SQL and Excel
- Build dashboards

Requirements:
- Python
- SQL
- Excel
- Data visualization
"""

In [49]:
resumes = [
    {
        "name": "Rahul Sharma",
        "degree": "BTech in Computer Science",
        "text": "Python, SQL, Excel, Power BI, ML. Built fraud detection model. Data Analyst Intern."
    },
    {
        "name": "Ananya Verma",
        "degree": "B.Sc in Data Science",
        "text": "Python, SQL, Tableau, Statistics. Customer segmentation project. Business Analyst Intern."
    },
    {
        "name": "Karan Mehta",
        "degree": "B.Com",
        "text": "SQL, Excel, Basic Python. Sales analysis project. No internship."
    },
    {
        "name": "Priya Singh",
        "degree": "BBA",
        "text": "Excel, Power BI, Basic SQL. Dashboard project. Internship in operations."
    },
    {
        "name": "Aman Gupta",
        "degree": "BA",
        "text": "MS Word, Communication, Teamwork. No technical experience."
    }
]

In [53]:
def evaluate_resume_logic(jd, resume_text):

    score = 0
    strengths = []
    gaps = []

    resume_lower = resume_text.lower()

    degree_lower = r["degree"].lower()

    if "data" in degree_lower or "computer" in degree_lower or "engineering" in degree_lower:
        score += 10
        strengths.append("Relevant educational background")
    else:
        gaps.append("Non-relevant education")

    if "python" in resume_lower:
        score += 20
        strengths.append("Python skills")
    else:
        gaps.append("Missing Python")

    if "sql" in resume_lower:
        score += 20
        strengths.append("SQL knowledge")
    else:
        gaps.append("Missing SQL")

    if "excel" in resume_lower:
        score += 10
        strengths.append("Excel proficiency")
    else:
        gaps.append("Missing Excel")

    if "power bi" in resume_lower or "tableau" in resume_lower:
        score += 10
        strengths.append("Data visualization tools")
    else:
        gaps.append("No visualization tools")


    if "intern" in resume_lower:
        score += 15
        strengths.append("Relevant experience")
    else:
        gaps.append("No relevant experience")


    if "project" in resume_lower or "model" in resume_lower:
        score += 10
        strengths.append("Hands-on project experience")
    else:
        gaps.append("No project experience")


    strengths = strengths[:3]
    gaps = gaps[:3]


    if score >= 80:
        recommendation = "Strong Fit"
    elif score >= 60:
        recommendation = "Moderate Fit"
    else:
        recommendation = "Not Fit"

    return {
        "Score": score,
        "Strengths": ", ".join(strengths),
        "Gaps": ", ".join(gaps),
        "Recommendation": recommendation
    }

In [54]:
results = []

for r in resumes:
    result = evaluate_resume_logic(jd, r["text"])

    results.append({
        "Candidate": r["name"],
        "Score": result["Score"],
        "Degree": r["degree"],
        "Strengths": result["Strengths"],
        "Gaps": result["Gaps"],
        "Recommendation": result["Recommendation"],
        "Decision": "Shortlist" if result["Score"] >= 60 else "Reject",
        "Reason": "High skill match and relevant experience" if result["Score"] >= 80
          else "Partial skill match with some gaps" if result["Score"] >= 60
          else "Low alignment with job requirements"
    })

In [55]:
df = pd.DataFrame(results)
df = df.sort_values(by="Score", ascending=False)

df

,Candidate,Score,Degree,Strengths,Gaps,Recommendation,Decision,Reason
0,Rahul Sharma,95,BTech in Computer Science,"Relevant educational background, Python skills...",,Strong Fit,Shortlist,High skill match and relevant experience
1,Ananya Verma,85,B.Sc in Data Science,"Relevant educational background, Python skills...",Missing Excel,Strong Fit,Shortlist,High skill match and relevant experience
2,Karan Mehta,75,B.Com,"Python skills, SQL knowledge, Excel proficiency","Non-relevant education, No visualization tools",Moderate Fit,Shortlist,Partial skill match with some gaps
3,Priya Singh,65,BBA,"SQL knowledge, Excel proficiency, Data visuali...","Non-relevant education, Missing Python",Moderate Fit,Shortlist,Partial skill match with some gaps
4,Aman Gupta,0,BA,,"Non-relevant education, Missing Python, Missin...",Not Fit,Reject,Low alignment with job requirements

In [56]:
df.reset_index(drop=True, inplace=True)
df.index = df.index + 1
df.index.name = "Rank"

df

,Candidate,Score,Degree,Strengths,Gaps,Recommendation,Decision,Reason
Rank,,,,,,,,
1,Rahul Sharma,95,BTech in Computer Science,"Relevant educational background, Python skills...",,Strong Fit,Shortlist,High skill match and relevant experience
2,Ananya Verma,85,B.Sc in Data Science,"Relevant educational background, Python skills...",Missing Excel,Strong Fit,Shortlist,High skill match and relevant experience
3,Karan Mehta,75,B.Com,"Python skills, SQL knowledge, Excel proficiency","Non-relevant education, No visualization tools",Moderate Fit,Shortlist,Partial skill match with some gaps
4,Priya Singh,65,BBA,"SQL knowledge, Excel proficiency, Data visuali...","Non-relevant education, Missing Python",Moderate Fit,Shortlist,Partial skill match with some gaps
5,Aman Gupta,0,BA,,"Non-relevant education, Missing Python, Missin...",Not Fit,Reject,Low alignment with job requirements

In [57]:
print("=== AI Resume Screening System ===")
print("Total Candidates:", len(df))
print("Shortlisted:", len(df[df["Decision"] == "Shortlist"]))
print("Rejected:", len(df[df["Decision"] == "Reject"]))

=== AI Resume Screening System ===
Total Candidates: 5
Shortlisted: 4
Rejected: 1

In [58]:
df.to_csv("resume_screening_results.csv", index=False)

In [59]:
from google.colab import files
files.download("resume_screening_results.csv")

In [60]:
print("=== Hiring Dashboard ===\n")

print("Top Candidates:")
display(df.head(3))

print("\nSummary:")
print("Total Candidates:", len(df))
print("Strong Fit:", len(df[df["Recommendation"] == "Strong Fit"]))
print("Moderate Fit:", len(df[df["Recommendation"] == "Moderate Fit"]))
print("Not Fit:", len(df[df["Recommendation"] == "Not Fit"]))

=== Hiring Dashboard ===

Top Candidates:

,Candidate,Score,Degree,Strengths,Gaps,Recommendation,Decision,Reason
Rank,,,,,,,,
1,Rahul Sharma,95,BTech in Computer Science,"Relevant educational background, Python skills...",,Strong Fit,Shortlist,High skill match and relevant experience
2,Ananya Verma,85,B.Sc in Data Science,"Relevant educational background, Python skills...",Missing Excel,Strong Fit,Shortlist,High skill match and relevant experience
3,Karan Mehta,75,B.Com,"Python skills, SQL knowledge, Excel proficiency","Non-relevant education, No visualization tools",Moderate Fit,Shortlist,Partial skill match with some gaps

Summary:
Total Candidates: 5
Strong Fit: 2
Moderate Fit: 2
Not Fit: 1

In [61]:
import pandas as pd

summary = df["Recommendation"].value_counts()
summary

Recommendation
Strong Fit      2
Moderate Fit    2
Not Fit         1
Name: count, dtype: int64